spring.application.name=nextware-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/nextware
spring.datasource.username=nextware
spring.datasource.password=nextware_dev_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.locations=filesystem:../database/migrations
spring.jpa.show-sql=false